### PR TITLE
Implementing crud operation interface for buses

### PR DESCRIPTION
**Pull request by Imaraika**
#### What does this PR do?
- Create a table for CRUD operations of bus
#### Description of Task to be completed?
- Add a table for:

    - Create Buses
    - Retrieve Buses
    - Update Buses
    - Delete Buses
#### How should this be manually tested?
   - Clone the github repository
   - run npm install
   - run npm run dev to start the dev server
   - Login and then navigate to Bus on the side menu

#### Any background context you want to provide?
N/A
#### What are the relevant Trello boards stories?
 - https://trello.com/c/NjgN1Qu0/50-create-crud-operation-interface-for-buses
#### Screenshots (if appropriate)
- 
image

#### Questions:
N/A

### CODE REVIEW

**Review by IRANKUND — CHANGES_REQUESTED** [review]
@Imaraika thank you for implementing crud ui for buses 
 i have 2 comments on your pr
=you can reduce the width of Create form make it equal to update form 
= increase the test coverage

**Comment by maximeish** [comment]
Good work on the UI, but if possible you can also center the table or give it full height of the container

**Comment by Imaraika** [comment]
> @Imaraika thank you for implementing crud ui for buses
> i have 2 comments on your pr
> =you can reduce the width of Create form make it equal to update form
> = increase the test coverage

Thank you Patrick I worked on the feedback. You can take a look on the PR again

**Comment by Imaraika** [comment]
> Good work on the UI, but if possible you can also center the table or give it full height of the container

thanks Maxime worked on it either I decided to give it the full height of the container

**Pull request closed without merging**
