### PR TITLE
ft: implemented crud features for routes

### PR DESCRIPTION
**Pull request by maximeish**
### What this PR does

- Create a table for CRUD operations of routes

### Task to be completed

Add a table for:

> - creating routes

> - retrieving routes

> - updating routes

> - deleting routes

- Add form validation and error handling

### Manual testing

- Clone the github repository

- run npm install

- run npm run dev to start the dev server

- Login and then navigate to Routes on the sidemenu 

### Background context
N/A

### Relevant pivotal tracker stories
https://trello.com/c/05QyQIHz/51-create-crud-operation-interface-for-routes

### Screenshots
image
image
image
image

### CODE REVIEW

**Review by IRANKUND — CHANGES_REQUESTED** [review]
Good work Maxime but i have some comment on this pr
=On create route cancil  button and create button can be on the same line 
=can you add link to landing page on the logo so that it will be easy for admin to go back to 
  landing page

**Comment by maximeish** [comment]
> Good work Maxime but i have some comment on this pr
> =On create route cancil button and create button can be on the same line
> =can you add link to landing page on the logo so that it will be easy for admin to go back to
> landing page

@IRANKUND I have worked on the feedback, you can review the changes now

**Review by joshwambere — COMMENTED** [review]
great work maxime 
->when you hit refresh while on routes it automatically goes to the dashboard if there is any way you can make it refresh but stay on routes that would be awesome.
->the input modal I think is too big, is almost the whole screen.

**Review by IRANKUND — APPROVED** [review]

**Comment by maximeish** [comment]
> great work maxime
> ->when you hit refresh while on routes it automatically goes to the dashboard if there is any way you can make it refresh but stay on routes that would be awesome.
> ->the input modal I think is too big, is almost the whole screen.

@joshwambere 

- when you refresh the page goes to its initial state so that is normal for it to start on the dashboard unless we try to store the current state in a database

- ok let me reduce the width of the modal

**Review by Rwandarushya — APPROVED** [review]
You did a great job @maximeish, the way you are adding the bus stop under the route is really cool, but I think for the starting point and destination user should use other input rather than just numbers. also as the back end team did, the name of the route  should be autogenerated. good job

**Comment by maximeish** [comment]
> You did a great job @maximeish, the way you are adding the bus stop under the route is really cool, but I think for the starting point and destination user should use other input rather than just numbers. also as the back end team did, the name of the route should be autogenerated. good job

@Rwandarushya I was following the mockup as it was using numbers for starting location and destination so there isn't a way for autogenerating the route name

**Review by Imaraika — APPROVED** [review]
I Cloned Your Branch for Reviewing your PR for my system All feature are well implemented and also I like the way you separated the file especially for styles and the table interface itself. Thanks.

**Review by malaba6 — APPROVED** [review]

**Pull request merged**
