### PR TITLE
Add mobile view and web view for Login Page

### PR DESCRIPTION
**Pull request by giranezafiacre**
What does this PR do?
Creating Login Page

Description of Task to be completed?
-create Login.js
-add emotion css and antd design
-create Login route
-create dumy Admin Login route

How should this be manually tested?
-download source code run 'npm i' and run npm run start and write 'http:localhost:8080' and click in 'Admin Login'
-Admin credentials are 'gunner@gmail.com' for email and '111111' for password

Any background context you want to provide?
N/A

What are the relevant trello board stories?
https://trello.com/c/uzpLNFSM/43-implement-login-page-design-using-the-new-mockup-design

Screenshots (if appropriate)
phoneVersion
gitmobileView
webView

#### Questions:
N/A

### CODE REVIEW

**Review by maximeish — DISMISSED** [review]
- you can try to remove the Login link from navbar on the Login page since it is on the same page

- also the admin login credentials should be provided in the PR description

**Comment by giranezafiacre** [comment]
@maximeish I am just respecting the design mockup because it was approved and also a user may want to logout and that feature of logout it in that navbar

**Comment by maximeish** [comment]
> @maximeish I am just respecting the design mockup because it was approved and also a user may want to logout and that feature of logout it in that navbar

Ok no problem. let us keep it the way it is

**Review by maximeish — CHANGES_REQUESTED** [review]
It's good that you fixed the CORS error but some thing to fix would be to:

- Not allow the user to view the Login page when they are already logged in

**Review by maximeish — APPROVED** [review]

**Pull request merged**
