### PR TITLE
ft: improving the landing page

### PR DESCRIPTION
**Pull request by maximeish**
### What this PR does

- Improving the UI of the landing page for both mobile and web view

### Task to be completed

- Add two separate logos for both mobile and web view

- Add hover effects to nav links

- improve the UI of the Sidemenu of mobile view by removing the top white area

### Manual testing

- Clone the github repository

- run npm install

- run npm run dev to start the dev server

- check mobile and web view of `http://localhost:8080/home`

### Background context
N/A

### Relevant pivotal tracker stories
N/A

### Screenshots
image

image

image

### CODE REVIEW

**Review by Monehin — CHANGES_REQUESTED** [review]
Kindly fix update test coverage for the changes

**Comment by maximeish** [comment]
> Kindly fix update test coverage for the changes

@Monehin yes I am working on it. It just included the changes I made on the CRUD for routes and I am removing them

**Review by Monehin — APPROVED** [review]
Looks good to me 👍  Would advise that would on the test coverage it's still below 90%.

**Review by Rwandarushya — APPROVED** [review]
Good job @maximeish , I see that all task you mentioned in your PR has been covered

**Comment by Rwandarushya** [comment]
In my opinion, I would also suggest if possible when a user clicks on one side view the other one should be closed.  I think there is no case in which the user would need to use both at the same time.
Screen Shot 2020-11-13 at 20 30 52

**Comment by maximeish** [comment]
> In my opinion, I would also suggest if possible when a user clicks on one side view the other one should be closed. I think there is no case in which the user would need to use both at the same time.
> Screen Shot 2020-11-13 at 20 30 52

@Rwandarushya I think that would make the user experience uncomfortable since the user has to re-open the same panel again whenever they want to make a few changes. So I think it would be better to leave the choices to the user

**Review by Monehin — APPROVED** [review]

**Pull request merged**
